### ISSUE TITLE
Incorrect SA arg type in mdns_query_recv

### ISSUE THREAD

**Issue by brimston3** [mjansson/mdns#1]
https://github.com/rampantpixels/mdns/blob/c3d4acab17919285f40800da5fb906161c4b1e1b/mdns.h#L693

`(struct sockaddr*)&saddr` should just be `saddr` like it is in mdns_discovery_recv(). As it is, this will almost certainly result in a segfault if any responses are received.

**Comment by mjansson** [comment]
Indeed! Fixed
