### ISSUE TITLE
Query multiple network interfaces

### ISSUE THREAD

**Issue by adisuciu** [mjansson/mdns#17]
I'm using your library to discover IIO services in my networks. It works fine for just one interface, however it looks like mdns_query_send, only sends out the query to the last enumerated interface (as far as I got with my tests). I can confirm this behavior in WireShark. 
I have several devices that emulate a network interface using a RNDIS driver and run a mDNS server on their interface. The goal is to find all the devices that implement this IIO service across all my interfaces (RNDIS or regular)

I'm running Windows 10 & MS Visual Studio 2019 
For reference:
https://github.com/analogdevicesinc/libiio/blob/dnssd-windows/dns_sd_windows.c#L126

**Comment by mjansson** [comment]
Yeah, I have code doing this on Windows at least, will bring it into the library

**Comment by rgetz** [comment]
@mjansson : if you have any code to test - let me know, and I can try it out on my systems. I think I'm running into the same issue.

**Comment by mjansson** [comment]
I've updated the open/setup socket functions in the library header, and the example code in mdns.c to support multiple interfaces.

So far only a Windows implementation on the interface enumeration, will do a posix compliant implementation asap.

**Comment by mjansson** [comment]
Should now be done, including some other cleanups

**Comment by rgetz** [comment]
Thanks - I will try it out.

**Comment by adisuciu** [comment]
Works great for us, thanks !
