### ISSUE TITLE
why mdns_services_query is const and just used for "_services._dns-sd._udp.local."?

### ISSUE THREAD

**Issue by ZhuChasel** [mjansson/mdns#19]
I think it's a good idea if this code can be widely-used for any local result. It seems it can only multicast 
"_services._dns-sd._udp.local."

**Comment by mjansson** [comment]
You use mdns_query_send to do specific service queries, see the example tool https://github.com/mjansson/mdns/blob/4f7f7942bd10eb3d67af48b5233cb84283d9639c/mdns.c#L252

**Comment by mjansson** [comment]
The mdns_services_query static is just a convenience to quickly send a DNS-SD packet. But yes, the code could be refactored to reuse more of the base packet layout.
