### ISSUE TITLE
error: ‘in4addr_any’ undeclared

### ISSUE THREAD

**Issue by rmokerone** [mjansson/mdns#20]
$ gcc -o mdns mdns.c
mdns.c: In function ‘open_service_sockets’:
mdns.c:285:24: error: ‘in4addr_any’ undeclared (first use in this function); did you mean ‘in6addr_any’?
   sock_addr.sin_addr = in4addr_any;
                        ^~~~~~~~~~~
                        in6addr_any
mdns.c:285:24: note: each undeclared identifier is reported only once for each function it appears in
OS: Ubuntu 18.04.4 LTS

How to solve this problem?

thanks~

**Comment by mjansson** [comment]
Sorry, that was introduced by the update to support multiple network interfaces, which I only had time to fully implement for Windows. Will do the POSIX port asap.

For now, you can just comment out the line `sock_addr.sin_addr = in4addr_any;`

**Comment by mjansson** [comment]
Should now be fixed
