### ISSUE TITLE
cppcheck reports Variable 'remain' is assigned a value that is never used.

### ISSUE THREAD

**Issue by rgetz** [mjansson/mdns#21]
https://github.com/mjansson/mdns/blob/ce2e4f789f06429008925ff8f18c22036e60201e/mdns.h#L1079

which looks like it is a correct warning?

**Comment by mjansson** [comment]
The warning is correct, that line is dead code at the moment (until support is added for multiple text records, then it will be needed)

**Comment by mjansson** [comment]
Fixed, thanks for the report

**Comment by rgetz** [comment]
Thanks
