### ISSUE TITLE
compile with MSVC without warnings.

### ISSUE THREAD

**Issue by rgetz** [mjansson/mdns#22]
We compile our MSVC projects with the following flags:
`/W4 /wd4200 /wd4127 /wd4100 /WX`
- `/W4` displays level 1, level 2, and level 3 warnings, and all level 4 (informational) warnings that aren't off by default. 
- `C4200` ignore nonstandard extension used : zero-sized array in struct (too many in libusb.h)
- `C4127`: ignore conditional expression is constant
- `C4100`: ignore unreferenced parameter; same as `-Wno-unused-parameter`
- `/WX` same as `-Werror`

to get things to compile - we needed to do:

Free free to use or ignore. Thanks

```
--- ../mdns/mdns.h      2020-05-22 10:59:35.848102185 -0400
+++ ./mdns.h    2020-05-22 11:00:41.592646263 -0400
@@ -470,7 +471,9 @@
        size_t cur = *offset;
        size_t end = MDNS_INVALID_POS;
        mdns_string_pair_t substr;
-       mdns_string_t result = {str, 0};
+      mdns_string_t result;
+      result.str = str;
+      result.length = 0;
        char* dst = str;
        size_t remain = capacity;
        do {
```

**Comment by mjansson** [comment]
Hopefully all the warnings should be ironed out now

**Comment by rgetz** [comment]
thanks
