### ISSUE TITLE
Not fully complaint due to UDP source port

### ISSUE THREAD

**Issue by MazdakFarzone** [mjansson/mdns#23]
I'm trying to communicate with a client running Zeroconf-python.
It has a custom service which avahi can find. Couldn't find it using this repo.

Identified this issue in `mdns.c` :
```int port = (mode == 2) ? MDNS_PORT : 0;
int sock = mdns_socket_open_ipv4(port);
if (sock < 0) {
   printf("Failed to open socket: %s\n", strerror(errno));
   return -1;
}
```
So running `--discovery` or `--query` would set the port to 0 making dynamic and random (right?)
[RFC 6763](https://tools.ietf.org/html/rfc6763) says the following:

> A compliant Multicast DNS querier, which implements the rules
   specified in this document, MUST send its Multicast DNS queries from
   UDP source port 5353 (the well-known port assigned to mDNS), and MUST
   listen for Multicast DNS replies sent to UDP destination port 5353 at
   the mDNS link-local multicast address (224.0.0.251 and/or its IPv6
   equivalent FF02::FB).

Tried setting `mode <=2` instead but wasn't successful,

**Comment by mjansson** [comment]
Thank you for the report, I will have a look at this and fix asap.

**Comment by mjansson** [comment]
So if I read that part of the spec correctly, all sockets doing mDNS/DNS-SD should always bind to local UDP port 5353?

**Comment by mjansson** [comment]
Should be updated on master now to always use port 5353
