### ISSUE TITLE
Support continuous queries

### ISSUE THREAD

**Issue by mjansson** [mjansson/mdns#25]
Implement support for a full featured service with continuous multicast queries as outlined in section 5.2 of RFC 6762 (https://tools.ietf.org/html/rfc6762#section-5)

**Comment by paulocoutinhox** [comment]
+1

**Comment by paulocoutinhox** [comment]
Hi,

It will be developed.

And thanks for this great library.

Thanks.

**Comment by mjansson** [comment]
I have looked into this and decided it is a task that is beyond the scope of this header-only library. Doing a full features continuous mDNS service in a non-allocating header library is just not feasible right now.

I might revisit this in the future, but for now it is put on the back burner.
