### ISSUE TITLE
--service response not valid

### ISSUE THREAD

**Issue by julsch90** [mjansson/mdns#26]
I try to use a mdns query service request from an ESP32. But the response is not valid. I try to find in your the problem in your code. Do you have some hints?

**Comment by mjansson** [comment]
Can you provide a bit more information on what exactly you are doing?

Are you using `mdns_query_send` to send a query?

If so, do you get responses at all in `mdns_query_recv` at all, but they are discarded?

Are you using the provided sample tool in `mdns.c` or using the header in your own code?

**Comment by mjansson** [comment]
I've done some updates and changes to improve compliance with the RFC, the example --service mode should now provide correct data for other mDNS services.

**Comment by gregjesl** [comment]
My setup uses this library for services and https://github.com/novotnyllc/Zeroconf for queries.  Prior to commit 7e1050d26bf9808ad25a841739ab17b7085d08a3 the Zeroconf was unable to find services advertised by this library.  Commit 7e1050d26bf9808ad25a841739ab17b7085d08a3 fixed the issue for me; I suspect it will resolve this issue as well.

**Comment by mjansson** [comment]
Thanks for reporting, will close this for now.

**Comment by julsch90** [comment]
Working know with the ESP32. Great thx
