### ISSUE TITLE
Transaction Id may violate the RFC definition?

### ISSUE THREAD

**Issue by Kxuan** [mjansson/mdns#27]
The [RFC documentation](https://tools.ietf.org/html/rfc6762#section-18.1) says 

```
   In multicast query messages, the Query Identifier SHOULD be set to
   zero on transmission.
    In multicast responses, including unsolicited multicast responses,
   the Query Identifier MUST be set to zero on transmission, and MUST be
   ignored on reception.
```

So it seems the line https://github.com/mjansson/mdns/blob/244e5788c10fc69ad9cdc3f2f4d967fe206b8441/mdns.h#L870
violate the documentation

**Comment by mjansson** [comment]
I should rename "transaction" to "query" to match the terminology of the RFC.

However, what this library currently implements is one-shot queries with unicast responses, and thus answers fall in the "legacy unicast response messages" part which states

"In legacy unicast response messages generated specifically in response to a particular (unicast or multicast) query, the Query Identifier MUST match the ID from the query message."

I chose to use the query ID as it provided filtering that I was interested in at the time, but perhaps it should be changed to comply with "the Query Identifier SHOULD be set to zero on transmission" in the RFC.

Or perhaps an optional additional argument to mdns_query_send that decides the query ID to use (and you can thus pass 0).

**Comment by mjansson** [comment]
I made the query ID explicit in the call to mdns_query_send, pass 0 to be fully compliant with the RFC "Query Identifier SHOULD be set to zero on transmission"

**Comment by Kxuan** [comment]
Thanks mjansson. That solve my problem.
