### ISSUE TITLE
Android and iOS

### ISSUE THREAD

**Issue by paulocoutinhox** [mjansson/mdns#33]
Hi,

It support android and ios?

Thanks.

**Comment by mjansson** [comment]
Android and iOS should now be supported with the latest ARM compatibility updates made.

**Comment by paulocoutinhox** [comment]
Hi,

This latest version is on conan repository?

Thanks.

**Comment by mjansson** [comment]
I don’t think so, but I don’t maintain that

**Comment by paulocoutinhox** [comment]
There is a tag/release for the new/current version with ARM support?

**Comment by mjansson** [comment]
There is now, 1.2
