### ISSUE TITLE
Theoretical Issue

### ISSUE THREAD

**Issue by RakshanPremsagar** [mjansson/mdns#35]
Hi there,
Since apologies for posting a theoretical query here. Well, this is not exactly related to the stack, however, it is about mDNS.

I have a server on my system, and when i run it, it advertises its services through mDNS in the network. 
The documentation says, the services are advertised using SRV records. However, I see PTR,TXT records as well.

Also, since it is advertising, is it not the case that, only response should be seen on wireshark. I see query and response as well. Please let me know.

Regards,
Rakshan

**Comment by mjansson** [comment]
Sorry for the (very) late answer. Example:

D:\mdns>mdns --query _spotify-connect._tcp.local.
Local IPv6 address: fe80::5e:b60e:dffe:c9a0%7
Local IPv4 address: 10.0.1.132
Opened 2 sockets for mDNS query
Sending mDNS query: _spotify-connect._tcp.local.
Reading mDNS query replies
10.0.1.100:5353 : answer _spotify-connect._tcp.local. PTR RX-V781 FA8AD8._spotify-connect._tcp.local. rclass 0x1 ttl 10 length 17
10.0.1.100:5353 : additional RX-V781 FA8AD8._spotify-connect._tcp.local. SRV RX-V781-FA8AD8.local. priority 0 weight 0 port 80
10.0.1.100:5353 : additional RX-V781 FA8AD8._spotify-connect._tcp.local. TXT VERSION = 1.0
10.0.1.100:5353 : additional RX-V781 FA8AD8._spotify-connect._tcp.local. TXT CPath = /goform/spotifyConfig
10.0.1.100:5353 : additional RX-V781-FA8AD8.local. A 10.0.1.100

So you query for a service, and get a PTR record for an instance, a SRV record mapping that instance to a hostname and port, then a couple of TXT records for custom data payload and then an A record for the IPv4 address of that hostname (in the SRV record).

Coupled together, the records tell you the IP address and the port to connect to for that service instance, and any custom data needed in the TXT records.
