### ISSUE TITLE
SIGBUS while parsing AAAA record

### ISSUE THREAD

**Issue by mariotaku** [mjansson/mdns#36]
This is quite weird as this issue only happen when I try to use mdns on my webOS TV. (Which is cross compiled with GCC 6.2.0). I made a patch to fix this crash, but it seems too weird so I'd like to create an issue instead of PR, to let you decide if this should be changed or not.

Crash site:
https://github.com/mjansson/mdns/blob/58b5d163abee957a7706c5ced3a15a5c24497e96/mdns.h#L1210

Patch:
```diff
@@ -1207,7 +1207,7 @@ mdns_record_parse_aaaa(const void* buffer, size_t size, size_t offset, size_t le
        addr->sin6_len = sizeof(struct sockaddr_in6);
 #endif
        if ((size >= offset + length) && (length == 16))
-               addr->sin6_addr = *(const struct in6_addr*)((const char*)buffer + offset);
+               memcpy(&(addr->sin6_addr), ((const char*)buffer + offset), 16);
        return addr;
 }

```

**Comment by mjansson** [comment]
Looks like an alignment issue, where there is a data member in the ipv6 address struct that requires alignment on the hardware executing it on your TV. Since the network packet data is unaligned by nature this causes issues.

The fix is correct.

**Comment by mjansson** [comment]
I'll look over the code and see if there are more places that would need a memcpy rather than an assignment to avoid alignment violations.

**Comment by mjansson** [comment]
I have a work in progress branch up for this, check #37 

Will do some additional testing on ARM hardware over the weekend

**Comment by mariotaku** [comment]
Thank you! After I compiled and run, `mdns_example` runs normally.
