### ISSUE TITLE
[Question] Respond to A and AAAA queries?

### ISSUE THREAD

**Issue by bram-nijenkamp** [mjansson/mdns#39]
Hi,

First of all thanks for this great library! I do however have a question.
Is it already possible to answer A and AAAA queries? I do see a generic answer function, but don't see any sample as to how to answer this. I did find the parse but that is used only when querying oneself?

Sincerely,
Bram Nijenkamp

**Comment by mjansson** [comment]
Will add a generalized answer function that will solve this

**Comment by bram-nijenkamp** [comment]
Thanks will look forward to it!!!

**Comment by mjansson** [comment]
This has now been implemented and the example code shows how to answer different record types
