### ISSUE TITLE
how can i add the TXT record like 'test=1'?

### ISSUE THREAD

**Issue by ShiverZm** [mjansson/mdns#40]
i use your demo, it is cool, it can be searched by Bonjour,when i publish service.
i want it work as MAC TV,so I need add some TXT record.

**Comment by mjansson** [comment]
You give the TXT record you want to send as last arguments to mdns_query_answer

I think the test program does this, iirc.

Or did you mean sending multiple TXT records in an answer? This is currently not supported, but something I can add.

**Comment by ShiverZm** [comment]
@mjansson yes,i want send multiple TXT record,i try do this by myself,but it did not work,would you mind adding this function?Thanks a lot.

**Comment by mjansson** [comment]
I will add a more generalized answer function that will also solve #39

**Comment by mjansson** [comment]
This has now been implemented, and the example code shows how to add multiple TXT records
