### ISSUE TITLE
DNS

### ISSUE THREAD

**Issue by pkalphaChen** [mjansson/mdns#41]
Hello,first of all thanks for this great library!  I have a question. How to access by domain name?  Can you give me an example? thank you.

**Comment by pkalphaChen** [comment]
And no broadcast packets were issued when DNS-SD was running.

**Comment by mjansson** [comment]
This library is intended for multicast dns, in the .local domain.

The mdns.c example program shows how to setup a socket on port 5353 and listen to dns-sd, and how to send an answer for your service.

**Comment by pkalphaChen** [comment]
I modified the .c example a little bit and wanted to integrate the code into the embedded device. Start the Fedora system in the virtual machine, use avahi-browse -a to search for the embedded device, and cannot access it through "hostname.local". I have been trying for many days, but I can’t succeed, because it is the first time to do it, so I need a little guidance. I kindly ask you to give a simple modified example, thank you very much!

**Comment by pkalphaChen** [comment]
Now you can access the device via "domain name. Local" in Fedora. You can use avahi-browse-r to parse out the device information, and the information is correct, but you can't scan the device using avahi-browse-a.

**Comment by mjansson** [comment]
The library did not handle questions for "ANY" records, and also handled DNS-SD queries with multiple questions in the wrong way.

This has been fixed, try the latest master branch.

**Comment by pkalphaChen** [comment]
Thank you very, very much! Problem solved!
