### ISSUE TITLE
splitting application vs mdns functions

### ISSUE THREAD

**Issue by rgetz** [mjansson/mdns#43]
Mattias:

First - thanks - we use this code in [libiio](https://github.com/analogdevicesinc/libiio/blob/master/dns_sd_windows.c) windows builds; and would like to keep up with your changes.

However, we need to cut up the file a little (to split out your main, which we don't need, and a few other things, to make it easier to use as a leaf function). I was wondering if it made sense to do the same thing here, which would allow easier tracking for others?

Thanks again
- Robin

**Comment by mjansson** [comment]
I don't know... I mean, the mdns.c is just an example usage of the actual library in the header. It's not meant for production use, just to show how you could potentially use the library functionality.

**Comment by rgetz** [comment]
Thanks - I guess we were looking at `mdns.c` as less of an example, and more of _the_ way to do things... 

For some things - there isn't a better way to do it, and we were looking at portions of that as "part" of the library...

If the intent is to be used as an example, not to be used verbatim - that's cool, we will just do that...

-Robin
