### ISSUE TITLE
User data in mdns_discovery_recv callback

### ISSUE THREAD

**Issue by IoanCosminSzanto** [mjansson/mdns#5]
Hello!
In the current implementation the callback called by mdns_discovery_recv does not permit to pass a pointer to a user data. I need this feature in order to aggregate all the DNS records which are being retrieved for an IP address.
Would you accept a pull request which implements this feature?

**Comment by mjansson** [comment]
Sounds useful, please do

**Comment by mjansson** [comment]
Merged, thanks!
