### ISSUE TITLE
Multiple Questions per Query

### ISSUE THREAD

**Issue by Muddasir-Shakil** [mjansson/mdns#58]
Hello,
I am looking for solution to implement LDS-ME for OPC UA. There I need multicast queries to discover SRV and TXT records of OPC UA Applications. I could send and receive them individually with mdns_query_send on port 5353. It allowed me to receive QM responses.  Since I am working with embedded devices it would be a nice to have "Multiple Questions per Query". 
How can I enable it in my application? 
Problem: mdns_query_send only send one question per query.
Thank you 
Muddasir Shakil

**Comment by mjansson** [comment]
I added a `mdns_multiquery_send` function which takes an array of name + record type structs to send multiple questions in the same packet.

**Comment by mjansson** [comment]
I read the RFC more carefully and added a dump mode to the example application to see what other implementation send, and to me it seems only the PTR records are shared records of the types this library currently use.

I've updated the answer functions (answer, announce and goodbye) to make sure PTR records are never sent with cache flush, while unique records are sent with cache flush on announce. This is now consistent with observed data from other implementations.
