### ISSUE TITLE
Multiple questions in muliquery responses

### ISSUE THREAD

**Issue by JM-deprecated** [mjansson/mdns#62]
We noticed that when sending a multiquery on the same service, querying for SRV, PTR, A, and AAAA records, the response contained multiple questions. The `mdns_query_recv` function, however, discards all responses with `questions > 1`. 

According to the RFC, the questions should simply be skipped (as is done later in the function):

```
   Multicast DNS responses MUST NOT contain any questions in the
   Question Section.  Any questions in the Question Section of a
   received Multicast DNS response MUST be silently ignored.  Multicast
   DNS queriers receiving Multicast DNS responses do not care what
   question elicited the response; they care only that the information
   in the response is true and accurate.
````
From what I've tested, simply removing the check for `questions > 1` seems to be adequate.

**Comment by mjansson** [comment]
Good catch, thanks! Makes sense, done.
